#!/usr/bin/env python3
"""Build the original Microforge portable sticker library using stdlib only.

This is an authoring/reproduction tool, not part of the registry runtime.
It emits small rigid glTF 2.0 GLBs plus exact editable procedural JSON sources,
then packages them as axm.sticker-library/v1. Geometry math is quantized before
serialization so exact generated bytes remain portable across supported hosts.
"""
from __future__ import annotations
import argparse
import base64
import hashlib
import json
import math
from pathlib import Path
import struct

SCHEMA = 'axm.sticker/v1'
INSTANCE = 'axm.sticker-instance/v1'
LIBRARY = 'axm.sticker-library/v1'
GLB = 'axm.sticker.glb-rigid/v1'
ASSEMBLY = 'axm.sticker.assembly-3d/v1'
ORIGIN = {
    'author':'AXM',
    'license':'CC0-1.0',
    'source':'Original Microforge part/library generated by tools/build_microforge_library.py',
}

def canonical(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(',',':'),
                      allow_nan=False).encode('utf-8')

def digest(value):
    return hashlib.sha256(canonical(value)).hexdigest()

def _q(value):
    return round(float(value),12)

def identity(tx=0, ty=0, tz=0):
    return [1.0,0.0,0.0,float(tx), 0.0,1.0,0.0,float(ty),
            0.0,0.0,1.0,float(tz), 0.0,0.0,0.0,1.0]

def ry(degrees, tx=0, ty=0, tz=0):
    angle=math.radians(degrees); c=_q(math.cos(angle)); s=_q(math.sin(angle))
    return [c,0.0,s,float(tx), 0.0,1.0,0.0,float(ty),
            -s,0.0,c,float(tz), 0.0,0.0,0.0,1.0]

def rz(degrees, tx=0, ty=0, tz=0):
    angle=math.radians(degrees); c=_q(math.cos(angle)); s=_q(math.sin(angle))
    return [c,-s,0.0,float(tx), s,c,0.0,float(ty),
            0.0,0.0,1.0,float(tz), 0.0,0.0,0.0,1.0]

def _quad(positions, normals, indices, corners, normal):
    start=len(positions)
    positions.extend(corners); normals.extend([normal]*4)
    indices.extend([start,start+1,start+2,start,start+2,start+3])

def _box():
    p=[]; n=[]; i=[]
    _quad(p,n,i,((-.5,-.5,.5),(.5,-.5,.5),(.5,.5,.5),(-.5,.5,.5)),(0.,0.,1.))
    _quad(p,n,i,((.5,-.5,-.5),(-.5,-.5,-.5),(-.5,.5,-.5),(.5,.5,-.5)),(0.,0.,-1.))
    _quad(p,n,i,((.5,-.5,.5),(.5,-.5,-.5),(.5,.5,-.5),(.5,.5,.5)),(1.,0.,0.))
    _quad(p,n,i,((-.5,-.5,-.5),(-.5,-.5,.5),(-.5,.5,.5),(-.5,.5,-.5)),(-1.,0.,0.))
    _quad(p,n,i,((-.5,.5,.5),(.5,.5,.5),(.5,.5,-.5),(-.5,.5,-.5)),(0.,1.,0.))
    _quad(p,n,i,((-.5,-.5,-.5),(.5,-.5,-.5),(.5,-.5,.5),(-.5,-.5,.5)),(0.,-1.,0.))
    return p,n,i

def _normal(a,b,c):
    ab=tuple(b[j]-a[j] for j in range(3)); ac=tuple(c[j]-a[j] for j in range(3))
    cross=(ab[1]*ac[2]-ab[2]*ac[1], ab[2]*ac[0]-ab[0]*ac[2],
           ab[0]*ac[1]-ab[1]*ac[0])
    length=math.sqrt(sum(value*value for value in cross))
    return tuple(_q(value/length) for value in cross)

def _pyramid():
    p=[]; n=[]; i=[]
    _quad(p,n,i,((-.5,-.5,-.5),(.5,-.5,-.5),(.5,-.5,.5),(-.5,-.5,.5)),(0.,-1.,0.))
    sides=[
        ((-.5,-.5,.5),(.5,-.5,.5),(0.,.5,0.)),
        ((.5,-.5,-.5),(-.5,-.5,-.5),(0.,.5,0.)),
        ((.5,-.5,.5),(.5,-.5,-.5),(0.,.5,0.)),
        ((-.5,-.5,-.5),(-.5,-.5,.5),(0.,.5,0.)),
    ]
    for side in sides:
        start=len(p); p.extend(side); n.extend([_normal(*side)]*3)
        i.extend([start,start+1,start+2])
    return p,n,i

def _cylinder(segments):
    p=[]; n=[]; indices=[]
    for index in range(segments):
        a0=2*math.pi*index/segments; a1=2*math.pi*(index+1)/segments
        c0,s0=_q(math.cos(a0)),_q(math.sin(a0))
        c1,s1=_q(math.cos(a1)),_q(math.sin(a1))
        p0=(_q(c0*.5),-.5,_q(s0*.5))
        p1=(_q(c1*.5),-.5,_q(s1*.5))
        p2=(p1[0],.5,p1[2]); p3=(p0[0],.5,p0[2])
        start=len(p); p.extend([p0,p1,p2,p3])
        n.extend([(c0,0.,s0),(c1,0.,s1),(c1,0.,s1),(c0,0.,s0)])
        indices.extend([start,start+1,start+2,start,start+2,start+3])
        top=len(p); p.extend([(0.,.5,0.),p3,p2]); n.extend([(0.,1.,0.)]*3)
        indices.extend([top,top+1,top+2])
        bottom=len(p); p.extend([(0.,-.5,0.),p1,p0]); n.extend([(0.,-1.,0.)]*3)
        indices.extend([bottom,bottom+1,bottom+2])
    for index in range(0,len(indices),3):
        indices[index+1],indices[index+2]=indices[index+2],indices[index+1]
    return p,n,indices

def _rgba(value):
    channels=[int(value[index:index+2],16) for index in range(1,len(value),2)]
    if len(channels)==3: channels.append(255)
    return [channel/255 for channel in channels]

def build_glb(spec):
    primitive=spec['primitives'][0]
    if primitive['type']=='box': positions,normals,indices=_box()
    elif primitive['type']=='pyramid': positions,normals,indices=_pyramid()
    else: positions,normals,indices=_cylinder(primitive.get('segments',16))
    binary=bytearray(); views=[]; accessors=[]
    def append(data,target):
        while len(binary)%4: binary.append(0)
        offset=len(binary); binary.extend(data); result=len(views)
        views.append({'buffer':0,'byteOffset':offset,'byteLength':len(data),'target':target})
        return result
    pv=append(b''.join(struct.pack('<fff',*row) for row in positions),34962)
    nv=append(b''.join(struct.pack('<fff',*row) for row in normals),34962)
    iv=append(b''.join(struct.pack('<H',index) for index in indices),34963)
    pa=len(accessors)
    accessors.append({'bufferView':pv,'componentType':5126,'count':len(positions),'type':'VEC3',
                      'min':[min(row[axis] for row in positions) for axis in range(3)],
                      'max':[max(row[axis] for row in positions) for axis in range(3)]})
    na=len(accessors)
    accessors.append({'bufferView':nv,'componentType':5126,'count':len(normals),'type':'VEC3'})
    ia=len(accessors)
    accessors.append({'bufferView':iv,'componentType':5123,'count':len(indices),'type':'SCALAR',
                      'min':[min(indices)],'max':[max(indices)]})
    document={
        'asset':{'version':'2.0','generator':'AXM Sticker Fabric Microforge deterministic GLB v0.1'},
        'scene':0,'scenes':[{'name':spec['name'],'nodes':[0]}],
        'nodes':[{'name':primitive['id'],'mesh':0,'translation':primitive['translation'],
                  'scale':primitive['size']}],
        'meshes':[{'name':primitive['id'],'primitives':[{
            'attributes':{'POSITION':pa,'NORMAL':na},'indices':ia,'material':0,'mode':4}]}],
        'materials':[{'name':primitive['id']+'-material','pbrMetallicRoughness':{
            'baseColorFactor':_rgba(primitive['material']['color']),
            'metallicFactor':primitive['material']['metallic'],
            'roughnessFactor':primitive['material']['roughness']}}],
        'accessors':accessors,'bufferViews':views,'buffers':[{'byteLength':len(binary)}],
        'extras':{'axmSpecificationSchema':spec['schema'],
                  'axmSpecificationSha256':digest(spec),'axmPrimitiveCount':1},
    }
    json_bytes=canonical(document); json_padded=json_bytes+b' '*((-len(json_bytes))%4)
    binary_padded=bytes(binary)+b'\x00'*((-len(binary))%4)
    total=12+8+len(json_padded)+8+len(binary_padded)
    body=(struct.pack('<4sII',b'glTF',2,total)
          +struct.pack('<II',len(json_padded),0x4E4F534A)+json_padded
          +struct.pack('<II',len(binary_padded),0x004E4942)+binary_padded)
    verify_glb(body)
    return body

def verify_glb(body):
    if len(body)<28: raise ValueError('GLB truncated')
    magic,version,total=struct.unpack('<4sII',body[:12])
    if magic!=b'glTF' or version!=2 or total!=len(body): raise ValueError('GLB header invalid')
    json_length,json_kind=struct.unpack('<II',body[12:20])
    if json_kind!=0x4E4F534A or json_length%4: raise ValueError('GLB JSON chunk invalid')
    document=json.loads(body[20:20+json_length].rstrip(b' ').decode('utf-8'))
    offset=20+json_length
    binary_length,binary_kind=struct.unpack('<II',body[offset:offset+8])
    if binary_kind!=0x004E4942 or binary_length%4 or offset+8+binary_length!=len(body):
        raise ValueError('GLB BIN chunk invalid')
    if document.get('asset',{}).get('version')!='2.0' or document.get('scene')!=0:
        raise ValueError('GLB glTF declaration invalid')
    if len(document.get('scenes',[]))!=1 or document.get('skins') or document.get('images'):
        raise ValueError('Microforge GLB must remain one rigid embedded scene')
    return document

PARTS=[
    ('micro-cube','Micro cube','box',[0.35,0.35,0.35],'#7F8B98',0.55,0.45,
     ['micro','primitive','shape-box','role-block']),
    ('micro-plate','Micro plate','box',[1.20,0.12,0.80],'#657684',0.65,0.40,
     ['micro','primitive','shape-box','role-panel']),
    ('micro-beam','Micro beam','box',[1.50,0.16,0.16],'#556773',0.70,0.38,
     ['micro','primitive','shape-box','role-structure']),
    ('micro-column','Micro column','box',[0.16,1.20,0.16],'#556773',0.70,0.38,
     ['micro','primitive','shape-box','role-structure']),
    ('micro-brace','Micro brace','box',[0.80,0.12,0.12],'#71828D',0.60,0.42,
     ['micro','primitive','shape-box','role-brace']),
    ('micro-pin','Micro pin','cylinder',[0.12,0.45,0.12],'#C17C4A',0.80,0.28,
     ['micro','primitive','shape-cylinder','role-fastener']),
    ('micro-axle','Micro axle','cylinder',[0.16,0.90,0.16],'#A8B0B6',0.85,0.24,
     ['micro','primitive','shape-cylinder','role-axle']),
    ('micro-hub','Micro hub','cylinder',[0.38,0.18,0.38],'#3C4B56',0.75,0.32,
     ['micro','primitive','shape-cylinder','role-hub']),
    ('micro-wheel','Micro wheel','cylinder',[0.68,0.18,0.68],'#252C31',0.35,0.65,
     ['micro','primitive','shape-cylinder','role-wheel']),
    ('micro-disc','Micro disc','cylinder',[0.34,0.08,0.34],'#5D6A72',0.65,0.36,
     ['micro','primitive','shape-cylinder','role-detail']),
    ('micro-cap','Micro cap','pyramid',[0.28,0.28,0.28],'#CF9B55',0.62,0.35,
     ['micro','primitive','shape-pyramid','role-cap']),
    ('micro-marker','Micro marker','pyramid',[0.16,0.32,0.16],'#30DDE7',0.20,0.30,
     ['micro','primitive','shape-pyramid','role-marker']),
]

def build_library():
    definitions={}; assets={}
    for sticker_id,name,kind,size,color,metallic,roughness,tags in PARTS:
        primitive={'id':'shape','type':kind,'size':size,'translation':[0,0,0],
                   'material':{'color':color,'metallic':metallic,'roughness':roughness}}
        if kind=='cylinder': primitive['segments']=16
        spec={'schema':'axm.procedural-3d/v0.1','name':name,'primitives':[primitive]}
        source=(json.dumps(spec,ensure_ascii=False,sort_keys=True,indent=2)+'\n').encode('utf-8')
        model=build_glb(spec)
        model_sha=hashlib.sha256(model).hexdigest(); source_sha=hashlib.sha256(source).hexdigest()
        assets[model_sha]=base64.b64encode(model).decode('ascii')
        assets[source_sha]=base64.b64encode(source).decode('ascii')
        definitions[sticker_id]={
            'schema':SCHEMA,'id':sticker_id,'version':1,'name':name,'tags':tags,
            'origin':dict(ORIGIN),'adapter':GLB,
            'attachment':{'space':'3d','socket':'mount','anchor':identity()},
            'recipe':{'model':'model'},
            'assets':{'model':model_sha,'editable-source':source_sha},
            'parameters':{},
        }
    def pin(sticker_id):
        definition=definitions[sticker_id]
        return {'id':sticker_id,'version':1,'digest':digest(definition)}
    def child(sticker_id, instance_id, frame):
        return {'instance':{'schema':INSTANCE,'id':instance_id,'sticker':pin(sticker_id),
                            'overrides':{},'placement':{}},
                'target':{'space':'3d','socket':'mount','frame':frame},
                'motion':None,'clip':None}
    def assembly(sticker_id,name,tags,children):
        definitions[sticker_id]={
            'schema':SCHEMA,'id':sticker_id,'version':1,'name':name,'tags':tags,
            'origin':dict(ORIGIN),'adapter':ASSEMBLY,
            'attachment':{'space':'3d','socket':'mount','anchor':identity()},
            'recipe':{'children':children},'assets':{},'parameters':{},
        }
    assembly('micro-corner-module','Micro corner module',
             ['micro','assembly','module','role-structure'],[
        child('micro-beam','beam-x',identity(.70,.08,0)),
        child('micro-beam','beam-z',ry(90,0,.08,.70)),
        child('micro-column','column',identity(0,.60,0)),
        child('micro-pin','pin',identity(0,.28,0)),
        child('micro-cap','cap',identity(0,1.30,0)),
    ])
    assembly('micro-wheel-module','Micro wheel module',
             ['micro','assembly','module','role-motion'],[
        child('micro-axle','axle',rz(90)),
        child('micro-hub','hub',rz(90)),
        child('micro-wheel','wheel',rz(90)),
        child('micro-disc','disc',rz(90,.11,0,0)),
    ])
    panel=[child('micro-plate','plate',identity())]
    for index,(x,z) in enumerate([(-.45,-.28),(.45,-.28),(-.45,.28),(.45,.28)]):
        panel.append(child('micro-pin',f'pin-{index}',identity(x,.14,z)))
    panel.append(child('micro-marker','marker',identity(0,.16,0)))
    assembly('micro-panel-module','Micro panel module',
             ['micro','assembly','module','role-panel'],panel)
    root=[]
    for index,(x,z) in enumerate([(-1.45,-1.0),(1.45,-1.0),(-1.45,1.0),(1.45,1.0)]):
        root.append(child('micro-corner-module',f'corner-{index}',identity(x,0,z)))
    for index,(x,z) in enumerate([(-1.75,-.62),(-1.75,.62),(1.75,-.62),(1.75,.62)]):
        root.append(child('micro-wheel-module',f'wheel-{index}',identity(x,.35,z)))
    for index,z in enumerate([-1.15,1.15]):
        root.append(child('micro-panel-module',f'panel-{index}',identity(0,.78,z)))
    root.extend([
        child('micro-beam','cross-x-a',identity(-.72,.35,0)),
        child('micro-beam','cross-x-b',identity(.72,.35,0)),
        child('micro-beam','cross-z-a',ry(90,0,.35,-.72)),
        child('micro-beam','cross-z-b',ry(90,0,.35,.72)),
        child('micro-column','mast-a',identity(-.55,.62,0)),
        child('micro-column','mast-b',identity(.55,.62,0)),
        child('micro-cube','core-block',identity(0,.42,0)),
        child('micro-brace','brace',ry(45,0,.72,0)),
    ])
    assembly('microforge-demo','Microforge nested demo',
             ['micro','assembly','demo','nested'],root)
    order=['microforge-demo','micro-corner-module','micro-wheel-module','micro-panel-module']
    order.extend(item[0] for item in PARTS)
    return {'schema':LIBRARY,
            'root':{'id':'microforge-demo','version':1,'digest':digest(definitions['microforge-demo'])},
            'definitions':[definitions[key] for key in order],
            'assets':dict(sorted(assets.items()))}

def main(argv=None):
    parser=argparse.ArgumentParser()
    parser.add_argument('output',type=Path)
    args=parser.parse_args(argv)
    library=build_library()
    args.output.parent.mkdir(parents=True,exist_ok=True)
    args.output.write_text(json.dumps(library,ensure_ascii=False,sort_keys=True,indent=2)+'\n',
                           encoding='utf-8')
    print(json.dumps({'output':str(args.output),'root':library['root'],
                      'definitions':len(library['definitions']),'assets':len(library['assets'])},
                     sort_keys=True))

if __name__=='__main__':
    main()
